DROP TABLE IF EXISTS testdb.de_100.sales_temp CASCADE;
CREATE TABLE testdb.de_100.sales_temp(
  	uuid varchar(255) PRIMARY KEY,
	created_at date,
	file_name varchar(255),
	sheet_name varchar(255),
	num_records int,
	reporting_period_start varchar(255),
	reporting_period_end varchar(255),
	sell_through_channel varchar(255),
	store_id varchar(255),
	store_name varchar(255),	
	region varchar(255),
	country varchar(255),
	state varchar(255),
	product_retailer_sku varchar(255),
	product_sku varchar(255),
	product_name varchar(255),
	product_size varchar(255),
	product_line varchar(255),
	currency varchar(255),
	total_quantity Decimal(20,2),
	total_value Decimal(20,2),
	type varchar(255));
